environment:
  matrix:
    - GENERATOR_NAME: "Visual Studio 12 2013"
    - GENERATOR_NAME: "Visual Studio 12 2013 Win64"
    - GENERATOR_NAME: "Visual Studio 12 2013 ARM"
    - GENERATOR_NAME: "Visual Studio 14 2015"
    - GENERATOR_NAME: "Visual Studio 14 2015 Win64"
    - GENERATOR_NAME: "Visual Studio 14 2015 ARM"

platform: x64
configuration: Release

build_script:
  - C:\projects\cal\testing\appveyor-scripts\build-test.bat
